version: "3.9"
services:
  SQLServer: 
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
     - "1433:1433"
    environment:
      SA_PASSWORD: "1234qqqQ"
      ACCEPT_EULA: "Y"
     
  ElasticSearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false 
    ports:
      - target: 9200
        published: 9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    environment:
     ELASTICSEARCH_HOSTS: http://host.docker.internal:9200 
    ports:
    - "5601:5601"    
    depends_on:
    - ElasticSearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672

  prometheus:
    image: ubuntu/prometheus
    container_name: prometheus
    ports:
      - "30090:9090"
    environment:
      - TZ=UTC
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "30091:3000"    